---
- name: Deploy Senticord Bot & Panel
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  vars_files:
    - ../group_vars/all/vault.yml

  pre_tasks:
    - name: Generate session_secret and store in vault if missing
      # Only runs if vault.yml doesn’t already contain session_secret
      when: "'session_secret' not in lookup('file','../group_vars/all/vault.yml')"
      local_action:
        module: command
        # Generate a 64-char random secret, encrypt it with ansible-vault, name it 'session_secret'
        cmd: >
          ansible-vault encrypt_string --vault-password-file ~/.vault_pass
          "{{ lookup('password','/dev/null length=64 chars=ascii_letters,digits') }}"
          --name 'session_secret'
      register: vault_secret

    - name: Append new session_secret into your vault file
      when: vault_secret.stdout is defined
      local_action:
        module: lineinfile
        path: ../group_vars/all/vault.yml
        line: "{{ vault_secret.stdout }}\n"
        insertafter: EOF

  tasks:
    - name: Ensure application directory exists
      file:
        path: /opt/senticord
        state: directory
        owner: dimitri
        group: dimitri
        mode: '0755'

    - name: Copy application code
      copy:
        src: /opt/discordbot-senticord/
        dest: /opt/senticord/
        owner: dimitri
        group: dimitri
        mode: '0755'

    - name: Install Python dependencies
      pip:
        requirements: /opt/senticord/requirements.txt
        executable: pip3

    - name: Install Node dependencies for panel
      shell: npm install --production
      args:
        chdir: /opt/senticord/panel

    - name: Write .env (bot & panel)
      copy:
        dest: /opt/senticord/.env
        owner: dimitri
        group: dimitri
        mode: '0600'
        content: |
          DISCORD_TOKEN={{ discord_token }}
          DISCORD_CLIENT_ID={{ discord_client_id }}
          DISCORD_CLIENT_SECRET={{ discord_client_secret }}
          REDIRECT_URI={{ redirect_uri }}
          BOT_PERMISSIONS=8
          CAPTCHA_TIMEOUT_MIN=20
          CAPTCHA_MAX_ATTEMPTS=2
          SESSION_SECRET={{ session_secret }}

    - name: Ensure systemd unit for Senticord Bot
      copy:
        dest: /etc/systemd/system/senticord-bot.service
        mode: '0644'
        content: |
          [Unit]
          Description=Senticord Discord Bot
          After=network.target

          [Service]
          Type=simple
          User=dimitri
          WorkingDirectory=/opt/senticord
          EnvironmentFile=/opt/senticord/.env
          ExecStart=/usr/bin/python3 /opt/senticord/bot.py
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target

    - name: Ensure systemd unit for Senticord Panel
      copy:
        dest: /etc/systemd/system/senticord-panel.service
        mode: '0644'
        content: |
          [Unit]
          Description=Senticord Admin Panel (Express/React)
          After=network.target

          [Service]
          Type=simple
          User=dimitri
          WorkingDirectory=/opt/senticord/panel
          EnvironmentFile=/opt/senticord/.env
          ExecStart=/usr/bin/npm start
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable & restart services
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      loop:
        - senticord-bot
        - senticord-panel
