---
- name: Deploy Senticord bot & panel
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - ../group_vars/all/vault.yml

  tasks:
    - name: Ensure app dir exists
      file:
        path: /opt/senticord
        state: directory
        owner: dimitri
        group: dimitri
        mode: '0755'

    - name: Copy application code
      synchronize:
        src: ../discordbot-senticord/
        dest: /opt/senticord/
        recursive: yes
      become_user: dimitri

    - name: Install Python deps
      pip:
        requirements: /opt/senticord/requirements.txt
        executable: pip3

    - name: Write .env from Vault
      copy:
        dest: /opt/senticord/.env
        owner: dimitri
        group: dimitri
        mode: '0600'
        content: |
          DISCORD_TOKEN={{ discord_token }}
          DISCORD_CLIENT_ID={{ discord_client_id }}
          DISCORD_CLIENT_SECRET={{ discord_client_secret }}
          REDIRECT_URI={{ redirect_uri }}
          OAUTH_STATE_SECRET={{ oauth_state_secret }}
          BOT_PERMISSIONS=8
          CAPTCHA_TIMEOUT_MIN=20
          CAPTCHA_MAX_ATTEMPTS=2

    - name: Write systemd unit for Senticord Bot
      copy:
        dest: /etc/systemd/system/senticord-bot.service
        mode: '0644'
        content: |
          [Unit]
          Description=Senticord Discord Bot
          After=network.target

          [Service]
          Type=simple
          User=dimitri
          WorkingDirectory=/opt/senticord
          EnvironmentFile=/opt/senticord/.env
          ExecStart=/usr/bin/python3 /opt/senticord/bot.py
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target

    - name: Write systemd unit for Senticord Panel
      copy:
        dest: /etc/systemd/system/senticord-panel.service
        mode: '0644'
        content: |
          [Unit]
          Description=Senticord Admin Panel
          After=network.target

          [Service]
          Type=simple
          User=dimitri
          WorkingDirectory=/opt/senticord
          EnvironmentFile=/opt/senticord/.env
          ExecStart=/usr/bin/python3 /opt/senticord/panel.py
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable & start Senticord Bot service
      systemd:
        name: senticord-bot
        enabled: yes
        state: restarted

    - name: Enable & start Senticord Panel service
      systemd:
        name: senticord-panel
        enabled: yes
        state: restarted
