---
- name: Deploy Senticord Bot & Panel
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  vars_files:
    - ../group_vars/all/vault.yml

  tasks:
    - name: Ensure application directory exists
      file:
        path: /opt/senticord
        state: directory
        owner: dimitri
        group: dimitri
        mode: '0755'

    - name: Copy application code to /opt/senticord
      copy:
        src: /opt/discordbot-senticord/    # adjust to wherever your code lives on the controller
        dest: /opt/senticord/
        owner: dimitri
        group: dimitri
        mode: '0755'
        # no 'recurse' needed—copy will traverse directories by default

    - name: Install Python dependencies
      pip:
        requirements: /opt/senticord/requirements.txt
        executable: pip3

    - name: Write environment file
      copy:
        dest: /opt/senticord/.env
        owner: dimitri
        group: dimitri
        mode: '0600'
        content: |
          DISCORD_TOKEN={{ discord_token }}
          DISCORD_CLIENT_ID={{ discord_client_id }}
          DISCORD_CLIENT_SECRET={{ discord_client_secret }}
          REDIRECT_URI={{ redirect_uri }}
          OAUTH_STATE_SECRET={{ oauth_state_secret }}
          BOT_PERMISSIONS=8
          CAPTCHA_TIMEOUT_MIN=20
          CAPTCHA_MAX_ATTEMPTS=2

    - name: Create systemd service for Senticord Bot
      copy:
        dest: /etc/systemd/system/senticord-bot.service
        mode: '0644'
        content: |
          [Unit]
          Description=Senticord Discord Bot
          After=network.target

          [Service]
          Type=simple
          User=dimitri
          WorkingDirectory=/opt/senticord
          EnvironmentFile=/opt/senticord/.env
          ExecStart=/usr/bin/python3 /opt/senticord/bot.py
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target

    - name: Create systemd service for Senticord Panel
      copy:
        dest: /etc/systemd/system/senticord-panel.service
        mode: '0644'
        content: |
          [Unit]
          Description=Senticord Admin Panel (Flask)
          After=network.target

          [Service]
          Type=simple
          User=dimitri
          WorkingDirectory=/opt/senticord
          EnvironmentFile=/opt/senticord/.env
          ExecStart=/usr/bin/python3 /opt/senticord/panel.py
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Discord Bot service
      systemd:
        name: senticord-bot
        enabled: yes
        state: restarted

    - name: Enable and start Admin Panel service
      systemd:
        name: senticord-panel
        enabled: yes
        state: restarted
