---
- name: Deploy Senticord Bot, Panel API & Nginx SPA
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  vars_files:
    - ../group_vars/all/vault.yml

  pre_tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload Nginx

  tasks:
    - name: Ensure /opt/senticord exists
      file:
        path: /opt/senticord
        state: directory
        owner: dimitri
        group: dimitri
        mode: '0755'

    - name: Copy application code to /opt/senticord
      copy:
        src: /opt/discordbot-senticord/
        dest: /opt/senticord/
        owner: dimitri
        group: dimitri
        mode: '0755'

    # ─── Bot & DB setup ───────────────────────────────────────────────
    - name: Install Python dependencies
      pip:
        requirements: /opt/senticord/requirements.txt
        executable: pip3

    - name: Run DB migrations
      shell: node /opt/senticord/database/migrate.js
      args:
        creates: /opt/senticord/senticord.db

    # ─── Panel API (Express) ─────────────────────────────────────────
    - name: Install Node deps for Panel API
      become_user: dimitri
      shell: npm install --production
      args:
        chdir: /opt/senticord/panel

    - name: Ensure static SPA dir exists
      file:
        path: /opt/senticord/panel/static
        state: directory
        owner: dimitri
        group: dimitri
        mode: '0755'

    # (static/index.html & static/app.js are already in your repo)

    # ─── Environment ─────────────────────────────────────────────────
    - name: Write .env for bot & panel
      copy:
        dest: /opt/senticord/.env
        owner: dimitri
        group: dimitri
        mode: '0600'
        content: |
          DISCORD_TOKEN={{ discord_token }}
          DISCORD_CLIENT_ID={{ discord_client_id }}
          DISCORD_CLIENT_SECRET={{ discord_client_secret }}
          REDIRECT_URI={{ redirect_uri }}
          BOT_PERMISSIONS=8
          CAPTCHA_TIMEOUT_MIN=20
          CAPTCHA_MAX_ATTEMPTS=2
          

    # ─── systemd services ─────────────────────────────────────────────
    - name: Create systemd unit for Discord Bot
      copy:
        dest: /etc/systemd/system/senticord-bot.service
        mode: '0644'
        content: |
          [Unit]
          Description=Senticord Discord Bot
          After=network.target

          [Service]
          Type=simple
          User=dimitri
          WorkingDirectory=/opt/senticord
          EnvironmentFile=/opt/senticord/.env
          ExecStart=/usr/bin/python3 /opt/senticord/bot.py
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target

    - name: Create systemd unit for Panel API
      copy:
        dest: /etc/systemd/system/senticord-panel.service
        mode: '0644'
        content: |
          [Unit]
          Description=Senticord Admin Panel API
          After=network.target

          [Service]
          Type=simple
          User=dimitri
          WorkingDirectory=/opt/senticord/panel
          EnvironmentFile=/opt/senticord/.env
          ExecStart=/usr/bin/npm start
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target

    # ─── Nginx reverse proxy ──────────────────────────────────────────
    - name: Deploy Nginx site for Panel SPA
      copy:
        dest: /etc/nginx/sites-available/senticord-panel
        mode: '0644'
        content: |
          server {
              listen 80;
              server_name panel.yourdomain.com;

              root /opt/senticord/panel/static;
              index index.html;

              # Serve SPA
              location / {
                try_files $uri /index.html;
              }

              # Proxy API & OAuth to Express
              location ~ ^/(api|auth)/ {
                proxy_pass http://127.0.0.1:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
              }
          }
      notify: Reload Nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/senticord-panel
        dest: /etc/nginx/sites-enabled/senticord-panel
        state: link
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded

    - name: Restart services
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - senticord-bot
        - senticord-panel
